### PR TITLE
- Info de Geoinquietos-lisboa

### PR DESCRIPTION
**Pull request by doublebyte1**
- Añadida información sobre el grupo Geoinquietos Lisboa.

### CODE REVIEW

**Comment by jsanz** [comment]
Data from you and Carlos is not correct, can you please complete them?

**Comment by doublebyte1** [comment]
I am sorry about that @jsanz: just fixed it with my last commit

**Comment by jsanz** [comment]
I had to do  small hotfix on your file on master but it's live and well 

http://geoinquietos.org/grupos/lisboa/

Cheers

**Comment by doublebyte1** [comment]
Thanks @jsanz! I created another [PR](https://github.com/geoinquietos-org/geoinquietos-org.github.io/pull/24), to fix an error on the url of the website

**Pull request merged**
