### PR TITLE
geoinquietos sc

### PR DESCRIPTION
**Pull request by jsanz**
Ey @51114u9, can you take a look? fix anything missing so we can publish :smile:

### CODE REVIEW

**Comment by jsanz** [comment]
ok fixed and moved contact to @YoViajo, I hope this is now OK

**Comment by YoViajo** [comment]
Gracias

Date: Thu, 3 Mar 2016 07:00:44 -0800

**Comment by jsanz** [comment]
OK to merge then?

On Thu, Mar 3, 2016 at 4:25 PM, YoViajo notifications@github.com wrote:

> Gracias
> 
> Date: Thu, 3 Mar 2016 07:00:44 -0800
> From: notifications@github.com
> To: geoinquietos-org.github.io@noreply.github.com
> CC: rcrmj@hotmail.com
> Subject: Re: [geoinquietos-org.github.io] geoinquietos sc (#13)
> 
> ok fixed and moved contact to @YoViajo, I hope this is now OK
> 
> —
> Reply to this email directly or view it on GitHub.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/geoinquietos-org/geoinquietos-org.github.io/pull/13#issuecomment-191813629
> .

## 

Jorge Sanz
Solutions Engineer
CartoDB · Map Your World's Data

**Comment by YoViajo** [comment]
yep

==========+++++++========
Eric Armijo
rcrmj@hotmail.com
==========+++++++========

Date: Thu, 3 Mar 2016 07:29:33 -0800

**Pull request merged**
